var i18n = $.extend({}, i18n || {}, {
    xgcalendar: {
        dateformat: {
            "fulldaykey": "MMddyyyy",
            "fulldayshow": "L d yyyy",
            "fulldayvalue": "M/d/yyyy",
            "Md": "W M/d",
            "Md3": "L d",
            "separator": "/",
            "year_index": 2,
            "month_index": 0,
            "day_index": 1,
            "day": "d",
            "sun": "Minggu",
            "mon": "Senin",
            "tue": "Selasa",
            "wed": "Rabu",
            "thu": "Kamis",
            "fri": "Jumat",
            "sat": "Sabtu",
            "jan": "Jan",
            "feb": "Feb",
            "mar": "Mar",
            "apr": "Apr",
            "may": "Mei",
            "jun": "Jun",
            "jul": "Jul",
            "aug": "Agust",
            "sep": "Sep",
            "oct": "Okt",
            "nov": "Nov",
            "dec": "Des"
        },
        "no_implemented": "Belum diimplementasikan",
        "to_date_view": "Klik untuk melihat tanggal sekarang",
        "i_undefined": "Undefined",
        "allday_event": "Semua jadwal per hari",
        "repeat_event": "Ulangi Jadwal",
        "time": "Waktu",
        "event": "Jadwal",
        "location": "Lokasi",
        "participant": "Peserta",
        "get_data_exception": "Exception ketika mendapatkan data",
        "new_event": "Tambah Jadwal",
        "confirm_delete_event": "Apakah anda akan menghapus jadwal ini? ",
        "confrim_delete_event_or_all": "Apakah Anda ingin mengulang semua jadwal atau hanya jadwal ini? \ r \ n Klik [OK] untuk menghapus acara ini, klik [Cancel] untuk menghapus semua acara",
        "data_format_error": "Data format error! ",
        "invalid_title": "Pelajaran Harus Dipilih",
        "invalid_titleguru": "Guru Harus Dipilih",
        "view_no_ready": "Tunjukan jika tidak siap",
        "example": "Contoh: Matematika ",
        "content": "Nama Jadwal",
        "create_event": "Simpan Jadwal",
        "update_detail": "Edit jadwal",
        "click_to_detail": "Lihat Jadwal",
        "i_delete": "Hapus",
        "day_plural": "Hari",
        "others": "Lainnya",
        "item": ""
    }
});
